### ISSUE TITLE
[NETFLIX] msgid "Please Check your credentials"

### ISSUE THREAD

**Issue by cube79** [notoco/Polskie-kodi#1]
msgctxt "#30009"
msgid "Please Check your credentials"
msgstr "Zweryfikuj poprawność wprowadzonych danych"
"Zweryfikuj poprawność swoich poświadczeń (użytkownik/hasło)"

**Comment by notoco** [comment]
Może 
Zweryfikuj poprawność swoich danych (użytkownik/hasło)?

**Comment by notoco** [comment]
W oryginale nie ma (użytkownik/hasło) - więc nie chciałbym tego dodawać. 
Może 
"Zweryfikuj poprawność swoich danych"
Ps - dopisujmy też której wtyczki dotyczy

**Comment by cube79** [comment]
Wiem, że w oryginale nie ma (użytkownik/hasło) , ale wydaje mi się to jasną i klarowną informacją nie pozostawiającą wątpliwości gdzie jest błąd.
To był mój pierwszy post na Githubie, specjalnie konto założyłem - wszedłem w gałąź Netflixa, więc myślałem, że zakładam Issue dotyczący niego. Ale dostosuję się na przyszłość :-)

**Comment by notoco** [comment]
Nie - spoko - to nie jest oficjalny fork ani nic - to tylko robocze tymczasowe rozwiązanie.
Sam wymyśliłem sobie te zasady 
Co do tej uwagi użytkownik/hasło - zgłoszę ją autorowi.

**Comment by mbebe** [comment]
Sprawdz dane logowania
:-)

**Comment by notoco** [comment]
Jak mistrz się pojawi to od razu trafia.
